trigger:
  - master

# You can specify a pool at the pipeline, stage, or job level.
pool:
  vmImage: 'Ubuntu-20.04'

resources:
  containers:
  - container: trion-ng-cli
    image: trion/ng-cli:latest
    options: --user 0:0
  - container: trion-ng-cli-karma
    image: trion/ng-cli-karma:latest
    options: --user 0:0
  - container: trion-ng-cli-e2e
    image: trion/ng-cli-e2e:latest
    options: --user 0:0

stages:
- stage: install   
  displayName: Install NPM Dependencies
  jobs:
  - job: install
    container: trion-ng-cli
    displayName: NPM-Install
    steps:
    - task: Cache@2
      displayName: Cache NPM modules
      inputs:
        key: 'npm | package-lock.json'
        path: '$(Build.SourcesDirectory)/node_modules'
        cacheHitVar: NPM_CACHE_RESTORED
    - script: |
        export CYPRESS_CACHE_FOLDER=./node_modules/.cypress_cache
        npm ci
      displayName: NPM CI
      condition: ne(variables.NPM_CACHE_RESTORED, 'true')

- stage: lint
  dependsOn: install
  displayName: Quality Checks
  jobs:
  - job: ngversion
    container: trion-ng-cli
    displayName: Angular Version check
    steps:
    - task: Cache@2
      displayName: Cache NPM modules
      inputs:
        key: 'npm | package-lock.json'
        path: '$(Build.SourcesDirectory)/node_modules'
    - script: ng version
      displayName: Check angular version
  - job: lint
    container: trion-ng-cli
    displayName: Lint
    dependsOn: ngversion
    steps:
    - task: Cache@2
      displayName: Cache NPM modules
      inputs:
        key: 'npm | package-lock.json'
        path: '$(Build.SourcesDirectory)/node_modules'
        cacheHitVar: NPM_CACHE_RESTORED
    - script: ng lint
      displayName: Run linter


- stage: test
  dependsOn:
  - install
  - lint
  displayName: Test
  jobs:
  - job: test
    container: trion-ng-cli-karma
    displayName: Run tests
    steps:
    - task: Cache@2
      displayName: Cache NPM modules
      inputs:
        key: 'npm | package-lock.json'
        path: '$(Build.SourcesDirectory)/node_modules'
    - script: ng test --watch false
      displayName: Component tests
  - job: e2etest
    container: trion-ng-cli-e2e
    displayName: Run end-to-end tests
    steps:
    - task: Cache@2
      displayName: Cache NPM modules
      inputs:
        key: 'npm | package-lock.json'
        path: '$(Build.SourcesDirectory)/node_modules'
    - script: |
        export CYPRESS_CACHE_FOLDER=./node_modules/.cypress_cache
        ng e2e --watch false
      displayName: e2e tests


- stage: build
  dependsOn:
  - install
  - lint
  displayName: Build artifact
  jobs:
  - job: build
    container: trion-ng-cli-karma
    displayName: Build artifact
    steps:
    - task: Cache@2
      displayName: Cache NPM modules
      inputs:
        key: 'npm | package-lock.json'
        path: '$(Build.SourcesDirectory)/node_modules'
    - script: ng build -c production
      displayName: Build app
    - script: tar -czf dist.tgz dist
      displayName: Package
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/dist'
        includeRootFolder: true
        archiveType: 'tar'
        archiveFile: '$(Build.ArtifactStagingDirectory)/dist.tgz'
        replaceExistingArchive: true
    - task: PublishBuildArtifacts@1
      displayName: 'Publish dist'
      inputs:
       PathtoPublish: '$(Build.ArtifactStagingDirectory)/dist.tgz'
       ArtifactName: 'dist'

- stage: publish
  dependsOn:
   - build
   - test
  displayName: Publish artifact
  jobs:
    - job: publish
      displayName: Publish artifact
      steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'dist'
          downloadPath: '$(Build.ArtifactStagingDirectory)'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)/dist/dist.tgz'
          artifactType: 'pipeline'
          artifactName: 'web-app'

